/**
 * Glossaire LED de base FR / ZH-CN.
 * Termes validés à valider avant la première utilisation en production.
 * Sources : documentation Unilumin, standards secteur LED, appels d'offres réels.
 */

export type SeedTerm = { fr: string; zh: string; category: string };

export const LED_BASE_GLOSSARY: SeedTerm[] = [
  // === Caractéristiques techniques cœur LED ===
  { fr: "pixel pitch", zh: "像素间距", category: "tech_core" },
  { fr: "pas de pixel", zh: "像素间距", category: "tech_core" },
  { fr: "cabinet", zh: "箱体", category: "tech_core" },
  { fr: "armoire", zh: "箱体", category: "tech_core" },
  { fr: "module", zh: "模组", category: "tech_core" },
  { fr: "panneau", zh: "面板", category: "tech_core" },
  { fr: "dalle LED", zh: "LED面板", category: "tech_core" },
  { fr: "écran LED", zh: "LED显示屏", category: "tech_core" },
  { fr: "afficheur LED", zh: "LED显示屏", category: "tech_core" },
  { fr: "mur LED", zh: "LED显示墙", category: "tech_core" },
  { fr: "mur d'images", zh: "视频墙", category: "tech_core" },
  { fr: "résolution", zh: "分辨率", category: "tech_core" },
  { fr: "densité de pixels", zh: "像素密度", category: "tech_core" },
  { fr: "pixels par module", zh: "每模组像素数", category: "tech_core" },
  { fr: "rapport d'aspect", zh: "宽高比", category: "tech_core" },
  { fr: "format d'image", zh: "宽高比", category: "tech_core" },

  // === Photométrie / colorimétrie ===
  { fr: "luminosité", zh: "亮度", category: "photometry" },
  { fr: "brillance", zh: "亮度", category: "photometry" },
  { fr: "nits", zh: "尼特", category: "photometry" },
  { fr: "cd/m²", zh: "cd/m²", category: "photometry" },
  { fr: "candela par mètre carré", zh: "坎德拉每平方米", category: "photometry" },
  { fr: "taux de contraste", zh: "对比度", category: "photometry" },
  { fr: "contraste", zh: "对比度", category: "photometry" },
  { fr: "niveau de gris", zh: "灰度等级", category: "photometry" },
  { fr: "profondeur de couleur", zh: "色深", category: "photometry" },
  { fr: "gamme de couleurs", zh: "色域", category: "photometry" },
  { fr: "température de couleur", zh: "色温", category: "photometry" },
  { fr: "gamma", zh: "伽马值", category: "photometry" },
  { fr: "calibrage", zh: "校准", category: "photometry" },
  { fr: "calibration", zh: "校准", category: "photometry" },
  { fr: "uniformité", zh: "均匀性", category: "photometry" },
  { fr: "HDR", zh: "HDR", category: "photometry" },
  { fr: "fréquence de rafraîchissement", zh: "刷新率", category: "photometry" },
  { fr: "taux de rafraîchissement", zh: "刷新率", category: "photometry" },
  { fr: "fréquence d'image", zh: "帧率", category: "photometry" },
  { fr: "angle de vision", zh: "可视角度", category: "photometry" },
  { fr: "angle de vue", zh: "可视角度", category: "photometry" },
  { fr: "distance de vision", zh: "观看距离", category: "photometry" },

  // === Technologies LED ===
  { fr: "SMD", zh: "SMD", category: "led_tech" },
  { fr: "COB", zh: "COB", category: "led_tech" },
  { fr: "DIP", zh: "DIP", category: "led_tech" },
  { fr: "chip LED", zh: "LED芯片", category: "led_tech" },
  { fr: "puce LED", zh: "LED芯片", category: "led_tech" },
  { fr: "IC de pilotage", zh: "驱动IC", category: "led_tech" },
  { fr: "driver IC", zh: "驱动IC", category: "led_tech" },
  { fr: "mode de balayage", zh: "扫描方式", category: "led_tech" },
  { fr: "scan statique", zh: "静态扫描", category: "led_tech" },
  { fr: "fine pitch", zh: "小间距", category: "led_tech" },
  { fr: "petit pas", zh: "小间距", category: "led_tech" },
  { fr: "micro LED", zh: "Micro LED", category: "led_tech" },
  { fr: "mini LED", zh: "Mini LED", category: "led_tech" },
  { fr: "LED transparent", zh: "透明LED", category: "led_tech" },
  { fr: "écran transparent", zh: "透明LED显示屏", category: "led_tech" },
  { fr: "écran courbe", zh: "弧形屏", category: "led_tech" },

  // === Contrôle & signalisation ===
  { fr: "carte de réception", zh: "接收卡", category: "control" },
  { fr: "carte d'émission", zh: "发送卡", category: "control" },
  { fr: "processeur vidéo", zh: "视频处理器", category: "control" },
  { fr: "processeur LED", zh: "LED视频处理器", category: "control" },
  { fr: "serveur média", zh: "媒体服务器", category: "control" },
  { fr: "système de contrôle", zh: "控制系统", category: "control" },
  { fr: "logiciel de lecture", zh: "播放软件", category: "control" },
  { fr: "logiciel de calibration", zh: "校准软件", category: "control" },
  { fr: "signal de synchronisation", zh: "同步信号", category: "control" },
  { fr: "Novastar", zh: "诺瓦星云", category: "control" },
  { fr: "Colorlight", zh: "卡莱特", category: "control" },
  { fr: "HDMI", zh: "HDMI", category: "control" },
  { fr: "DVI", zh: "DVI", category: "control" },
  { fr: "fibre optique", zh: "光纤", category: "control" },
  { fr: "câble de signal", zh: "信号线", category: "control" },
  { fr: "câble de données", zh: "数据线", category: "control" },
  { fr: "câble d'alimentation", zh: "电源线", category: "control" },

  // === Électrique & environnement ===
  { fr: "consommation électrique", zh: "功耗", category: "electrical" },
  { fr: "consommation maximale", zh: "最大功耗", category: "electrical" },
  { fr: "consommation moyenne", zh: "平均功耗", category: "electrical" },
  { fr: "tension d'entrée", zh: "输入电压", category: "electrical" },
  { fr: "fréquence d'alimentation", zh: "电源频率", category: "electrical" },
  { fr: "distribution électrique", zh: "配电", category: "electrical" },
  { fr: "protection contre les surtensions", zh: "浪涌保护", category: "electrical" },
  { fr: "mise à la terre", zh: "接地", category: "electrical" },
  { fr: "indice de protection", zh: "IP防护等级", category: "electrical" },
  { fr: "IP65", zh: "IP65", category: "electrical" },
  { fr: "IP54", zh: "IP54", category: "electrical" },
  { fr: "IP43", zh: "IP43", category: "electrical" },
  { fr: "température de fonctionnement", zh: "工作温度", category: "environment" },
  { fr: "température de stockage", zh: "存储温度", category: "environment" },
  { fr: "humidité de fonctionnement", zh: "工作湿度", category: "environment" },
  { fr: "ventilation", zh: "通风", category: "environment" },
  { fr: "dissipation thermique", zh: "散热", category: "environment" },
  { fr: "sans ventilateur", zh: "无风扇", category: "environment" },
  { fr: "durée de vie", zh: "使用寿命", category: "environment" },
  { fr: "MTBF", zh: "平均无故障工作时间", category: "environment" },
  { fr: "MTTR", zh: "平均修复时间", category: "environment" },

  // === Installation / mécanique ===
  { fr: "installation intérieure", zh: "室内安装", category: "install" },
  { fr: "installation extérieure", zh: "户外安装", category: "install" },
  { fr: "intérieur", zh: "室内", category: "install" },
  { fr: "extérieur", zh: "户外", category: "install" },
  { fr: "semi-extérieur", zh: "半户外", category: "install" },
  { fr: "location", zh: "租赁", category: "install" },
  { fr: "installation fixe", zh: "固定安装", category: "install" },
  { fr: "maintenance avant", zh: "前维护", category: "install" },
  { fr: "maintenance arrière", zh: "后维护", category: "install" },
  { fr: "module magnétique", zh: "磁吸模组", category: "install" },
  { fr: "fixation murale", zh: "壁挂", category: "install" },
  { fr: "suspension", zh: "吊装", category: "install" },
  { fr: "pied de sol", zh: "落地支架", category: "install" },
  { fr: "structure porteuse", zh: "承重结构", category: "install" },
  { fr: "flight case", zh: "飞行箱", category: "install" },
  { fr: "hauteur", zh: "高度", category: "install" },
  { fr: "largeur", zh: "宽度", category: "install" },
  { fr: "profondeur", zh: "深度", category: "install" },
  { fr: "épaisseur", zh: "厚度", category: "install" },
  { fr: "dimensions", zh: "尺寸", category: "install" },
  { fr: "poids", zh: "重量", category: "install" },

  // === Séries Unilumin (verrouillées) ===
  { fr: "BNX", zh: "BNX系列", category: "unilumin" },
  { fr: "LST", zh: "LST系列", category: "unilumin" },
  { fr: "UGN2", zh: "UGN2系列", category: "unilumin" },
  { fr: "UIM3", zh: "UIM3系列", category: "unilumin" },
  { fr: "URMIII", zh: "URMⅢ系列", category: "unilumin" },
  { fr: "URM III", zh: "URMⅢ系列", category: "unilumin" },
  { fr: "UMini", zh: "UMini系列", category: "unilumin" },
  { fr: "Umate", zh: "Umate系列", category: "unilumin" },
  { fr: "Unilumin", zh: "洲明", category: "unilumin" },

  // === Business / appel d'offres ===
  { fr: "appel d'offres", zh: "招标", category: "tender" },
  { fr: "cahier des charges", zh: "技术规格书", category: "tender" },
  { fr: "cahier des prescriptions spéciales", zh: "特殊技术规范书", category: "tender" },
  { fr: "CPS", zh: "技术规格书", category: "tender" },
  { fr: "bordereau des prix unitaires", zh: "单价明细表", category: "tender" },
  { fr: "BPU", zh: "单价明细表", category: "tender" },
  { fr: "DPGF", zh: "详细价格明细", category: "tender" },
  { fr: "devis", zh: "报价单", category: "tender" },
  { fr: "cotation", zh: "报价", category: "tender" },
  { fr: "offre commerciale", zh: "商务报价", category: "tender" },
  { fr: "offre technique", zh: "技术方案", category: "tender" },
  { fr: "fournisseur", zh: "供应商", category: "tender" },
  { fr: "sous-traitant", zh: "分包商", category: "tender" },
  { fr: "maître d'ouvrage", zh: "业主", category: "tender" },
  { fr: "maître d'œuvre", zh: "项目管理方", category: "tender" },
  { fr: "lot", zh: "标段", category: "tender" },
  { fr: "prestation", zh: "服务", category: "tender" },
  { fr: "délai de livraison", zh: "交货期", category: "tender" },
  { fr: "ETD", zh: "预计交货时间", category: "tender" },
  { fr: "ETA", zh: "预计到货时间", category: "tender" },
  { fr: "garantie", zh: "保修期", category: "tender" },
  { fr: "service après-vente", zh: "售后服务", category: "tender" },
  { fr: "SAV", zh: "售后服务", category: "tender" },
  { fr: "pièces détachées", zh: "备件", category: "tender" },
  { fr: "pièces de rechange", zh: "备件", category: "tender" },
  { fr: "installation sur site", zh: "现场安装", category: "tender" },
  { fr: "mise en service", zh: "调试", category: "tender" },
  { fr: "réception provisoire", zh: "初步验收", category: "tender" },
  { fr: "réception définitive", zh: "最终验收", category: "tender" },
  { fr: "formation", zh: "培训", category: "tender" },
  { fr: "maintenance", zh: "维护", category: "tender" },
  { fr: "maintenance préventive", zh: "预防性维护", category: "tender" },
  { fr: "maintenance corrective", zh: "故障维修", category: "tender" },
  { fr: "support technique", zh: "技术支持", category: "tender" },

  // === Finance / Incoterms ===
  { fr: "prix unitaire", zh: "单价", category: "finance" },
  { fr: "prix total", zh: "总价", category: "finance" },
  { fr: "total HT", zh: "未税总价", category: "finance" },
  { fr: "hors taxes", zh: "未税", category: "finance" },
  { fr: "TTC", zh: "含税总价", category: "finance" },
  { fr: "toutes taxes comprises", zh: "含税", category: "finance" },
  { fr: "TVA", zh: "增值税", category: "finance" },
  { fr: "USD", zh: "美元", category: "finance" },
  { fr: "EUR", zh: "欧元", category: "finance" },
  { fr: "MAD", zh: "摩洛哥迪拉姆", category: "finance" },
  { fr: "dirham marocain", zh: "摩洛哥迪拉姆", category: "finance" },
  { fr: "CIF", zh: "CIF (成本、保险加运费)", category: "finance" },
  { fr: "FOB", zh: "FOB (船上交货)", category: "finance" },
  { fr: "DDP", zh: "DDP (完税后交货)", category: "finance" },
  { fr: "EXW", zh: "EXW (工厂交货)", category: "finance" },
  { fr: "Incoterms", zh: "国际贸易术语", category: "finance" },
  { fr: "conteneur", zh: "集装箱", category: "finance" },
  { fr: "liste de colisage", zh: "装箱单", category: "finance" },
  { fr: "facture proforma", zh: "形式发票", category: "finance" },
  { fr: "facture commerciale", zh: "商业发票", category: "finance" },
  { fr: "conditions de paiement", zh: "付款条件", category: "finance" },
  { fr: "acompte", zh: "预付款", category: "finance" },
  { fr: "solde", zh: "尾款", category: "finance" },
];
